name: Plagiarism Check

on:
  pull_request:
    paths:
      - 'assignments/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Check for plagiarism
      run: |
        python scripts/check_plagiarism.py ${{ github.event.pull_request.head.ref }}/assignments/new_submission.cpp
      env:
        NEW_SUBMISSION: ${{ github.event.pull_request.head.ref }}/assignments/new_submission.cpp
